### ISSUE TITLE
nixos.org redirect to the canonical domain and other concerns

### ISSUE THREAD

**Issue by deviantsemicolon** [nix-rfc-canonical-domain/rfcs#9]
Whichever domain gets decided on(hopefully not nix.dev because nix is more than a development tool), I think nixos.org should act as a redirect url to the new domain. This would prevent old urls in stuff like youtube videos and guides from breaking

**Comment by infinisil** [comment]
Could be improved, but redirects are mentioned already: https://github.com/nix-rfc-canonical-domain/rfcs/blob/canonical-domain/rfcs/1000-canonical-domain.md#redirects

**Comment by deviantsemicolon** [comment]
ok great
